apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    app: frontend
  name: frontend
  #annotations:
  #  linkerd.io/inject: enabled
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate 
  template: 
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: gcr.io/sopes2-331802/frontend:v0
        name: frontend-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: servicio-para-front
  namespace: default
  labels:
    app: frontend
spec:
  selector:
      app: frontend
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Deployment
metadata:
  name: backend
  namespace: default
  labels:
    app: backend
  #annotations:
    #linkerd.io/inject: enabled
spec:
  selector:
    app: backend
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  type: ClusterIP
