apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    app: frontend
  name: frontend
  annotations:
    linkerd.io/inject: enabled
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate 
  template: 
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: gcr.io/sopes2-331802/prueba1:v0
        name: react-app
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: servicio-para-front
  namespace: default
  labels:
    app: frontend
spec:
  selector:
      app: frontend
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: servicio-para-back
  namespace: default
  labels:
    app: nombre_app_back
  #annotations:
    #linkerd.io/inject: enabled
spec:
  selector:
    app: nombre_app_back
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: servicio-para-back-prueba-lb
  namespace: default
  labels:
    app: nombre_app_back
spec:
  selector:
      app: nombre_app_back
  ports:
    - port: 9080
      targetPort: 9080
  type: LoadBalancer
  