version: "3.9"

services:
    backend:
        container_name: server1
        restart: always
        build: .
        ports:
          - "5000:5000"
        links:
          - basedatos
        volumes:
          - .:/usr/src/app
        networks: 
          - networkapi 

    mongo:
        container_name: mongo
        image: mongo
        ports: 
          - "27018:27017"
        networks: 
          - networkapi
        volumes:
          - data:/data/db
        logging:
          driver: none

networks:
  networkapi: 

volumes:
  data:
